### ISSUE TITLE
Character entity reference

### ISSUE THREAD

**Issue by jim-rosales** [Aaron-Day/ColmarAcademy#3]
When adding the ampersand symbol to your HTML file, it is best practice to add it via its [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

In this case, all you need to do is replace `&` with `&amp;` 

https://github.com/Aaron-Day/ColmarAcademy/blob/e1196b30845612126a5b1b5eda881be2a512a61a/index.html#L81

**Comment by Aaron-Day** [comment]
Updated ampersands
